from app.domain.performance.value_objects._enum import GovernedEnum


class CoachingAuditEvent(GovernedEnum):
    COACHING_SESSION_CREATED = "COACHING_SESSION_CREATED"
    COACHING_SESSION_UPDATED = "COACHING_SESSION_UPDATED"
    COACHING_SESSION_CLOSED = "COACHING_SESSION_CLOSED"
    COACHING_OPPORTUNITY_CREATED = "COACHING_OPPORTUNITY_CREATED"
    COMMITMENT_CREATED = "COMMITMENT_CREATED"
    COMMITMENT_COMPLETED = "COMMITMENT_COMPLETED"
    COMMITMENT_MISSED = "COMMITMENT_MISSED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    NOTE_CREATED = "NOTE_CREATED"
    PRIVATE_NOTE_VIEWED = "PRIVATE_NOTE_VIEWED"
    TIMELINE_EVENT_CREATED = "TIMELINE_EVENT_CREATED"
    COACHING_ACCESS_DENIED = "COACHING_ACCESS_DENIED"
    COACHING_RECORD_MODIFICATION_REJECTED = (
        "COACHING_RECORD_MODIFICATION_REJECTED"
    )
