from enum import Enum


class WorkspaceAuditEvent(Enum):
    SUPERVISOR_WORKSPACE_VIEWED = "SUPERVISOR_WORKSPACE_VIEWED"
    SUPERVISOR_PRIORITY_QUEUE_VIEWED = (
        "SUPERVISOR_PRIORITY_QUEUE_VIEWED"
    )
    TEAM_PERFORMANCE_VIEWED = "TEAM_PERFORMANCE_VIEWED"
    AGENT_PROFILE_VIEWED = "AGENT_PROFILE_VIEWED"
    EMPLOYEE_TIMELINE_VIEWED = "EMPLOYEE_TIMELINE_VIEWED"
    COACHING_WORKSPACE_VIEWED = "COACHING_WORKSPACE_VIEWED"
    SUPERVISOR_WORKSPACE_ACCESS_DENIED = (
        "SUPERVISOR_WORKSPACE_ACCESS_DENIED"
    )
    RESTRICTED_WORKSPACE_DATA_SUPPRESSED = (
        "RESTRICTED_WORKSPACE_DATA_SUPPRESSED"
    )
    PRIVATE_NOTE_ACCESS_DENIED = "PRIVATE_NOTE_ACCESS_DENIED"
    LEADERSHIP_NOTE_ACCESS_DENIED = "LEADERSHIP_NOTE_ACCESS_DENIED"
    CROSS_TENANT_WORKSPACE_ACCESS_DENIED = (
        "CROSS_TENANT_WORKSPACE_ACCESS_DENIED"
    )
